name: 'Set up Node.js'
description: 'Install Node.js and development dependencies'

inputs:
  node-version:
    description: 'Node.js version to install'
    default: '18'

  registry-url:
    description: Registry to configure for publish

  install-dependencies:
    description: 'Run `pnpm install`'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Install pnpm ${{ inputs.pnpm-version }}'
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    - name: 'Install Node.js ${{ inputs.node-version }}'
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: 'Install dependencies'
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: pnpm install --frozen-lockfile
