import {
  mdiCameraOutline,
  mdiVideoOutline,
  mdiAlertCircleOutline,
  mdiAlertOutline,
  mdiCancel,
  mdiBroadcastOff,
  mdiPlus,
  mdiClose,
  mdiContentCopy,
  mdiMinus,
  mdiSend,
  mdiUndo,
  mdiBroadcast,
  mdiDownload,
  mdiImageFilterCenterFocus,
  mdiArrowExpandAll,
  mdiChevronDown,
  mdiMenu,
  mdiDotsHorizontal,
  mdiArrowUp,
  mdiCheck,
  mdiOpenInNew,
  mdiHelpCircleOutline,
  mdiCameraFlipOutline,
  mdiArrowTopRightBottomLeft,
  mdiRefresh,
  mdiInformationOutline,
  mdiPauseCircleOutline,
  mdiPlayCircleOutline,
  mdiLogout,
  mdiInstagram,
  mdiContentSaveOutline,
  mdiPencilOutline,
  mdiStopCircleOutline,
  mdiTwitter,
  mdiLinkedin,
  mdiTrashCanOutline,
  mdiCog,
  mdiFilterOutline,
  mdiGithub,
  mdiFileDownloadOutline,
  mdiCheckCircle,
  mdiAlertCircle,
  mdiCreditCardOutline,
  mdiAccountMultiple,
} from '@mdi/js';

export const paths: Record<string, string> = {
  broadcast: mdiBroadcast,
  cancel: mdiCancel,
  check: mdiCheck,
  close: mdiClose,
  cog: mdiCog,
  download: mdiDownload,
  instagram: mdiInstagram,
  linkedin: mdiLinkedin,
  logout: mdiLogout,
  github: mdiGithub,
  menu: mdiMenu,
  minus: mdiMinus,
  plus: mdiPlus,
  refresh: mdiRefresh,
  send: mdiSend,
  twitter: mdiTwitter,
  undo: mdiUndo,
  'account-multiple': mdiAccountMultiple,
  'alert-circle': mdiAlertCircle,
  'alert-circle-outline': mdiAlertCircleOutline,
  'alert-outline': mdiAlertOutline,
  'arrow-expand-all': mdiArrowExpandAll,
  'arrow-top-right-bottom-left': mdiArrowTopRightBottomLeft,
  'arrow-up': mdiArrowUp,
  'broadcast-off': mdiBroadcastOff,
  'camera-flip-outline': mdiCameraFlipOutline,
  'camera-outline': mdiCameraOutline,
  'check-circle': mdiCheckCircle,
  'chevron-down': mdiChevronDown,
  'content-copy': mdiContentCopy,
  'content-save-outline': mdiContentSaveOutline,
  'credit-card-outline': mdiCreditCardOutline,
  'dots-horizontal': mdiDotsHorizontal,
  'file-download-outline': mdiFileDownloadOutline,
  'filter-outline': mdiFilterOutline,
  'help-circle-outline': mdiHelpCircleOutline,
  'image-filter-center-focus': mdiImageFilterCenterFocus,
  'information-outline': mdiInformationOutline,
  'open-in-new': mdiOpenInNew,
  'pause-circle-outline': mdiPauseCircleOutline,
  'pencil-outline': mdiPencilOutline,
  'play-circle-outline': mdiPlayCircleOutline,
  'stop-circle-outline': mdiStopCircleOutline,
  'trash-can-outline': mdiTrashCanOutline,
  'video-outline': mdiVideoOutline,
};
