import '../../prime.css'
import './notify/index.svelte'
import './badge/index.svelte'
import './breadcrumbs/index.svelte'
import './button/index.svelte'
import './collapse/index.svelte'
import './input/index.svelte'
import './radio/index.svelte'
import './select/index.svelte'
import './slider/index.svelte'
import './switch/index.svelte'
import './tabs/index.svelte'
import { loadFonts } from '../lib/add-styles'

loadFonts().catch(error => console.error(error))
