name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint 💅
        run: pnpm lint

  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpm check

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Playwright Browsers
        run: pnpm --filter @viamrobotics/prime-ui exec playwright install --with-deps chromium

      - name: Test
        run: pnpm test
